version: '3'

services:
  blog-api:
    image: bitnami/postgresql:latest
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 8080:5432
    environment:
      - POSTGRESQL_USERNAME=${POSTGRES_USER}
      - POSTGRESQL_PASSWORD=docker={POSTGRES_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRES_DB}
volumes:
  pgdata:
